services:
  streamlit:
    image: streamlit-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REGISTRY_HOST=registry.codeocean.allenneuraldynamics.org
    ports:
      - "8501:8501"
    volumes:
      - ..:/root/capsule:cached
      - /mnt/data:/data:ro
    depends_on:
      - rclone
    command: streamlit run /root/capsule/code/streamlit_app.py 
    
  rclone:
    image: rclone/rclone:latest
    volumes:
      - /mnt/data:/data:rshared
      - ./mount_all.sh:/mount_all.sh:ro
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    entrypoint: ["/bin/sh", "-c"]
    command: ["/mount_all.sh"]
