#!/usr/bin/env bash
set -e


# using abc_atlas_access.abc_atlas_cache.manifest only, only dep is pydantic
pip install --no-deps https://github.com/AllenInstitute/abc_atlas_access/archive/v3.0.0.tar.gz